auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: untitled
url: http://poornigga.github.com
feed: /atom.xml
author_info: <a href="http://poornigga.github.com/">大狗</a>
