auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: untitled
url: http://poornigga.github.io
feed: /atom.xml
author_info: <a href="http://poornigga.github.io/">大狗</a>
